### ISSUE TITLE
undefined method `verify_latest_version' for FastlaneCore::UpdateChecker:Class (NoMethodError)

### ISSUE THREAD

**Issue by romainbiard** [fastlane/codes#15]
Hello,

After updating codes, I didn't manage to run it again.
Seems to miss something in fastlane-core.

Here are the traces.
Thank you !

Romain

macbook-pro-de-romain-2:~ romainbiard$ codes
/Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/lib/codes.rb:11:in `<module:Codes>': undefined method `verify_latest_version' for FastlaneCore::UpdateChecker:Class (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/lib/codes.rb:8:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/codes-0.2.1/bin/codes:5:in `<top (required)>'
	from /usr/local/bin/codes:23:in `load'
	from /usr/local/bin/codes:23:in `<main>'

**Comment by KrauseFx** [comment]
Thanks, nice catch, I'll push a new version shortly.

**Comment by KrauseFx** [comment]
I just pushed an update :rocket:
