### ISSUE TITLE
Fail when app is not available in the US App Store - Known fix

### ISSUE THREAD

**Issue by ohoachuck** [fastlane/codes#17]
It appears that Apple search API use US as default country.
If the app is not available in the US AppStore, then search API can't find it.

Steps to reproduce when searching to an app that is not available on US AppStore:
https://itunes.apple.com/lookup?id=338986109 => search API does not find the app.
https://itunes.apple.com/lookup?id=338986109&country=FR => search API does find the app.

A possible (probably) easy fix would need to add an extra option for country (-c || --country) in codes and update iTunesSearchApi.fetch* to include country if specified.

I'm sorry, my ruby is very basic (to not say null) and I'm afraid it's safer that you guys fix it directly in stead of me firing a risky pull request. :(

Olivier.

**Comment by lacostej** [comment]
lacostej/fastlane_core@78f3f0c20fe86f6e0aa31e40877f09389afdec08 could provide the support for this in fastlane_core

**Comment by ohoachuck** [comment]
Hello, you might have missed a #{suffix} for 
fetch_url("https://itunes.apple.com/lookup?bundleId=#{app_identifier}")
see screenshot.
<img width="949" alt="screen shot 2015-08-31 at 17 53 12" src="https://cloud.githubusercontent.com/assets/1560305/9583079/958b3aaa-5009-11e5-95aa-31f12415b552.png">

Olivier.

**Comment by lacostej** [comment]
I _had_ forgotten it. Already fixed on the latest PR:

https://github.com/fastlane/fastlane_core/pull/29

:)

**Comment by lacostej** [comment]
Fixed by #19

**Comment by KrauseFx** [comment]
Thanks @lacostej :rocket:

**Comment by ohoachuck** [comment]
Coo, thanx!
