### ISSUE TITLE
it would be nice if you could display all the APPID

### ISSUE THREAD

**Issue by sfransen** [fastlane/codes#5]
Please add command to display all the APPID in the app store.

**Comment by lacostej** [comment]
Would this really belong to codes ?

**Comment by KrauseFx** [comment]
No, absolutely not, I forgot to close/move this issue. That would be part of `spaceship`, which we're currently building :+1:

**Comment by sfransen** [comment]
What is spaceship?

Sent from my iPhone5

On May 20, 2015, at 10:11 AM, Felix Krause <notifications@github.com<mailto:notifications@github.com>> wrote:


No, absolutely not, I forgot to close/move this issue. That would be part of spaceship, which we're currently building [:+1:]

**Comment by KrauseFx** [comment]
@sfransen Still a secret, will be revealed soon hopefully. If you are subscribed to the `fastlane` newsletter or follow me on Twitter, you'll hear about it :+1:
