### ISSUE TITLE
redeem-now

### ISSUE THREAD

**Issue by danwie** [fastlane/codes#7]
Would it be possible to change (or add a new option) to use redeem-now.com instead of the default redeem url?

CODE_URL = "http://redeem-now.com/[[code]]"

Redeem-Now.com is a 100% free tool that lets you redeem codes automatically. But it also have instructions to redeem codes manually. Example: http://redeem-now.com/KLFSDAJLDFAK

**Comment by KrauseFx** [comment]
This would be possible, but I'm not sure to have redeem-now as a part of `codes`.

**Comment by lacostej** [comment]
This is solved by #8 by using

    codes --format "%c,http://redeem-now.com/%c" ....

**Comment by KrauseFx** [comment]
Thanks @lacostej :+1:
